#!/bin/sh

if [ -n "$APPVEYOR_BUILD_FOLDER" ]; then
	cd $APPVEYOR_BUILD_FOLDER
fi

for repo in devops test-data; do
	if [ ! -d external/project-renard/$repo ]; then
		git clone https://github.com/project-renard/$repo.git external/project-renard/$repo || return $?
	fi
done
. external/project-renard/devops/ENV.sh
