#!/bin/bash

if [ "$TRAVIS_OS_NAME" == "linux" ]; then
	# NOTE: we only run coverage on Linux.
	if [ -n "$COVERAGE" ] && [ "$COVERAGE" != "0" ]; then
		command cpanm -nq Moo List::AllUtils PPI IPC::Open2
		echo "Applying PPI transformation"
		sh $SCRIPT_BASE/from-curie/apply-ppi-xform-for-coverage
	fi
fi

true
