Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.ssh.forward_x11 = true
  config.vm.synced_folder "../../curie/", "/home/vagrant/curie/"
  config.vm.provision "shell", path: "./provision.sh"
  config.vm.provision :shell, privileged: false, path: "./perlbrewSetup.sh"
  config.vm.provision :shell, privileged: false, path: "./cpanmSetup.sh"
end
