#!/bin/sh

# git checkout --  lib/ t/lib/
find lib t/lib -type f -name '*.pm' -print -exec  perl -I$RENARD_SCRIPT_BASE/from-curie -Ilib -It/lib -MPPIFPXform -E 'my $xform = PPIFPXform->new; $xform->file("{}");'  \;
# git diff
