#!/bin/bash

source ~/perl5/perlbrew/etc/bashrc
source ~/.bashrc.project-renard
perlbrew install perl-5.20.3
perlbrew install-cpanm
perlbrew switch perl-5.20.3
cd $(_repo_dir curie)

# do not run tests because these may fail when not in interactive shell
cpanm --notest Term::ReadKey

cpanm --installdeps .
cpanm Dist::Zilla
