#!/bin/bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install build-essential vim curl wget libgirepository1.0-dev libgdl-3-5 gobject-introspection libgtk-3-dev
sudo apt-get -y install gir1.2-gdl-3 libpoppler-glib-dev poppler-utils mupdf-tools git libglib-object-introspection-perl
sudo apt-get -y install --no-install-recommends glade
sudo apt-get -y install libssl-dev

echo "Adding the ENV settings"
cat <<'EOF' >> ~vagrant/.bashrc.project-renard
for ENV_PATH in ~/project-renard/devops/ENV.sh ~/project-renard/devops/devops/ENV.sh; do
	if [ -f $ENV_PATH ]; then
		. $ENV_PATH
	fi
done
EOF
echo "source ~/.bashrc.project-renard" >> ~vagrant/.bashrc
