#!/bin/bash

brew update
brew install Caskroom/cask/osxfuse
brew install homebrew/fuse/sshfs

mkdir -p ~/.ssh/socket
echo "Host *
ControlMaster auto
ControlPath ~/.ssh/socket/%r@%h-%p
ControlPersist 600

Host 10.0.2.2
IdentityFile ~/.ssh/id_host
" > ~/.ssh/config
